behaviors:
  Inter1:
    trainer_type: sac
    hyperparameters:
      batch_size: 24
      buffer_size: 240000
      learning_rate: 3.0e-3
      learning_rate_schedule: linear 
     
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 1.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 1
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 2
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 1
    threaded: true